name = "webcounter-api"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[d1_databases]]
binding = "DB"
database_name = "webcounter"
database_id = "e196aad3-d612-4761-8f3c-af5bec711824"
migrations_dir = "migrations"
